#!/bin/bash
# can be run remotely using ssh do2 'bash -s' < scripts/build
set -e

cd ~/aviationweather
git checkout master
git pull
mkdir -p dist

cd go
go build -o ../dist/metar_scraper mattdee123.com/aviationweather/scraping/cmd/metar_scraper
